apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - name: web
        image: 12110161/kubenetes-predict
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
      imagePullSecrets:
      - name: kubenetes-predict